import { TOrdersTableData, TOrdersTableHeader } from '../types/order.types'

export const ordersTableHeaderMenu: TOrdersTableHeader[] = [
    {
        id: 1,
        name: 'Numer',
    },
    {
        id: 2,
        name: 'Klient',
    },
    {
        id: 3,
        name: 'Data przyjęcia',
    },
    {
        id: 4,
        name: 'Ostatnia modyfikacja',
    },
    {
        id: 5,
        name: 'Serwisant',
    },
    {
        id: 6,
        name: 'Status',
    },
]

export const ordersTableFakeData: TOrdersTableData[] = [
    {
        id: 1,
        client: 'Jimmie',
        createdAt: '5/9/2021',
        updatedAt: '4/27/2021',
        owner: 'Corey',
        status: 2,
    },
    {
        id: 2,
        client: 'Fionnula',
        createdAt: '7/6/2021',
        updatedAt: '6/4/2021',
        owner: 'Jeromy',
        status: 1,
    },
    {
        id: 3,
        client: 'Asher',
        createdAt: '6/28/2021',
        updatedAt: '12/19/2020',
        owner: 'Kenneth',
        status: 3,
    },
    {
        id: 4,
        client: 'Taffy',
        createdAt: '1/18/2021',
        updatedAt: '1/26/2021',
        owner: 'Aretha',
        status: 1,
    },
    {
        id: 5,
        client: 'Jory',
        createdAt: '9/11/2020',
        updatedAt: '1/30/2021',
        owner: 'Ilene',
        status: 3,
    },
    {
        id: 6,
        client: 'Morgen',
        createdAt: '9/24/2020',
        updatedAt: '8/14/2020',
        owner: 'Daniella',
        status: 3,
    },
    {
        id: 7,
        client: 'Gusti',
        createdAt: '10/29/2020',
        updatedAt: '3/7/2021',
        owner: 'Bondie',
        status: 2,
    },
    {
        id: 8,
        client: 'Edithe',
        createdAt: '11/10/2020',
        updatedAt: '3/7/2021',
        owner: 'Friedrick',
        status: 2,
    },
    {
        id: 9,
        client: 'Libbey',
        createdAt: '8/3/2020',
        updatedAt: '10/14/2020',
        owner: 'Jaine',
        status: 3,
    },
    {
        id: 10,
        client: 'Orlando',
        createdAt: '7/24/2021',
        updatedAt: '4/27/2021',
        owner: 'Morty',
        status: 3,
    },
    {
        id: 11,
        client: 'Orella',
        createdAt: '4/15/2021',
        updatedAt: '1/15/2021',
        owner: 'Walsh',
        status: 2,
    },
    {
        id: 12,
        client: 'Neysa',
        createdAt: '3/8/2021',
        updatedAt: '5/2/2021',
        owner: 'Federica',
        status: 2,
    },
    {
        id: 13,
        client: 'Kristoffer',
        createdAt: '9/4/2020',
        updatedAt: '10/24/2020',
        owner: 'Bonni',
        status: 1,
    },
    {
        id: 14,
        client: 'Kristin',
        createdAt: '7/22/2021',
        updatedAt: '6/1/2021',
        owner: 'Oberon',
        status: 2,
    },
    {
        id: 15,
        client: 'Christophorus',
        createdAt: '11/2/2020',
        updatedAt: '7/7/2021',
        owner: 'Cordie',
        status: 3,
    },
]
